# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/ANS_mtm_impl/ANS_mtm_impl/ANS_mtm_impl.srcs/sources_1/bd/ans_design/ip/ans_design_auto_pc_0/ans_design_auto_pc_0.xci
# IP: The module: 'ans_design_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/ANS_mtm_impl/ANS_mtm_impl/ANS_mtm_impl.gen/sources_1/bd/ans_design/ip/ans_design_auto_pc_0/ans_design_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ans_design_auto_pc_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/ANS_mtm_impl/ANS_mtm_impl/ANS_mtm_impl.srcs/sources_1/bd/ans_design/ip/ans_design_auto_pc_0/ans_design_auto_pc_0.xci
# IP: The module: 'ans_design_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/ANS_mtm_impl/ANS_mtm_impl/ANS_mtm_impl.gen/sources_1/bd/ans_design/ip/ans_design_auto_pc_0/ans_design_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ans_design_auto_pc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
